- hosts: kubernetes
  become: yes
  vars:
    dir_name: "testing"
  tasks:
  - name: Mkdir /home/dir
    file: 
      path=/home/{{dir_name}}
      state=directory
    become: yes
    become_user: root
